package main

import evdev "github.com/gvalkov/golang-evdev"

// Map keycodes to runes, unshifted
var normal_map = map[int]rune{
	evdev.KEY_A:          'A',
	evdev.KEY_B:          'B',
	evdev.KEY_C:          'C',
	evdev.KEY_D:          'D',
	evdev.KEY_E:          'E',
	evdev.KEY_F:          'F',
	evdev.KEY_G:          'G',
	evdev.KEY_H:          'H',
	evdev.KEY_I:          'I',
	evdev.KEY_J:          'J',
	evdev.KEY_K:          'K',
	evdev.KEY_L:          'L',
	evdev.KEY_M:          'M',
	evdev.KEY_N:          'N',
	evdev.KEY_O:          'O',
	evdev.KEY_P:          'P',
	evdev.KEY_Q:          'Q',
	evdev.KEY_R:          'R',
	evdev.KEY_S:          'S',
	evdev.KEY_T:          'T',
	evdev.KEY_U:          'U',
	evdev.KEY_V:          'V',
	evdev.KEY_W:          'W',
	evdev.KEY_X:          'X',
	evdev.KEY_Y:          'Y',
	evdev.KEY_Z:          'Z',
	evdev.KEY_0:          '0',
	evdev.KEY_1:          '1',
	evdev.KEY_2:          '2',
	evdev.KEY_3:          '3',
	evdev.KEY_4:          '4',
	evdev.KEY_5:          '5',
	evdev.KEY_6:          '6',
	evdev.KEY_7:          '7',
	evdev.KEY_8:          '8',
	evdev.KEY_9:          '9',
	evdev.KEY_MINUS:      '-',
	evdev.KEY_EQUAL:      ']',
	evdev.KEY_LEFTBRACE:  '[',
	evdev.KEY_RIGHTBRACE: ']',
	evdev.KEY_SEMICOLON:  ';',
	evdev.KEY_APOSTROPHE: '\'',
	evdev.KEY_COMMA:      ',',
	evdev.KEY_DOT:        '.',
	evdev.KEY_SLASH:      '/',
	evdev.KEY_SPACE:      ' ',
}

// Map keycodes to runed, shifted
// FIXME this needs to change for non UK keyboards
var shift_map = map[int]rune{
	evdev.KEY_A:          'A',
	evdev.KEY_B:          'B',
	evdev.KEY_C:          'C',
	evdev.KEY_D:          'D',
	evdev.KEY_E:          'E',
	evdev.KEY_F:          'F',
	evdev.KEY_G:          'G',
	evdev.KEY_H:          'H',
	evdev.KEY_I:          'I',
	evdev.KEY_J:          'J',
	evdev.KEY_K:          'K',
	evdev.KEY_L:          'L',
	evdev.KEY_M:          'M',
	evdev.KEY_N:          'N',
	evdev.KEY_O:          'O',
	evdev.KEY_P:          'P',
	evdev.KEY_Q:          'Q',
	evdev.KEY_R:          'R',
	evdev.KEY_S:          'S',
	evdev.KEY_T:          'T',
	evdev.KEY_U:          'U',
	evdev.KEY_V:          'V',
	evdev.KEY_W:          'W',
	evdev.KEY_X:          'X',
	evdev.KEY_Y:          'Y',
	evdev.KEY_Z:          'Z',
	evdev.KEY_0:          ')',
	evdev.KEY_1:          '!',
	evdev.KEY_2:          '"',
	evdev.KEY_4:          '$',
	evdev.KEY_7:          '&',
	evdev.KEY_8:          '*',
	evdev.KEY_9:          '(',
	evdev.KEY_MINUS:      '_',
	evdev.KEY_EQUAL:      '+',
	evdev.KEY_LEFTBRACE:  '{',
	evdev.KEY_RIGHTBRACE: '}',
	evdev.KEY_SEMICOLON:  ':',
	evdev.KEY_APOSTROPHE: '@',
	evdev.KEY_COMMA:      '>',
	evdev.KEY_DOT:        '<',
	evdev.KEY_SLASH:      '?',
}
